### ISSUE TITLE
LS_stat/LS_p

### ISSUE THREAD

**Issue by marie-zz** [cuelee/pleio#8]
Hi! Could I please ask what the LS_stat/LS_p columns in the output file refer to? Is this the LRT statistic?

**Comment by cuelee** [comment]
Hi, Marie, 

LS_stat and LS_p columns represent Lin-Sulivan's fixed effect (FE) statistic and its p-value, respectively.
Please refer to the following paper for more information.
-----------------------------------------------------------------------------------------------------------------------
Lin, D.Y. and P.F. Sullivan, Meta-analysis of genome-wide association studies with overlapping subjects. Am J Hum Genet, 2009. 85(6): p. 862-72.

Thanks, 
Cue Hyunkyu Lee

**Comment by marie-zz** [comment]
Thank you!
